### ISSUE TITLE
dev-qt/qtwebkit-5.212.0_pre20200309-r6 doesn't build with latest stable icu-75.1

### ISSUE THREAD

**Issue by efferre79** [stefantalpalaru/gentoo-overlay#157]
ICU 75.1 supports only cxx with std >=17

I get the compiler error:

```
FAILED: Source/WTF/wtf/CMakeFiles/WTF.dir/unicode/icu/CollatorICU.cpp.o
/usr/bin/x86_64-pc-linux-gnu-g++ -DBUILDING_QT__=1 -DBUILDING_WITH_CMAKE=1 -DBUILDING_WTF -DHAVE_CONFIG_H=1 -DQT_ASCII_CAST_WARNINGS -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_DYNAMIC_CAST -DQT_NO_EXCEPTIONS -DQT_USE_QSTRINGBUILDER -I/var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20200309-r6/work/qtwebkit-5.212.0-alpha4_build/Source/WTF/wtf -I/var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20200309-r6/work/qtwebkit-5.212.0-alpha4/Source/WTF/wtf -I/var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20200309-r6/work/qtwebkit-5.212.0-alpha4/Source/bmalloc -I/var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20200309-r6/work/qtwebkit-5.212.0-alpha4/Source/WTF -I/var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20200309-r6/work/qtwebkit-5.212.0-alpha4/Source/WTF/wtf/dtoa -I/var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20200309-r6/work/qtwebkit-5.212.0-alpha4/Source/WTF/wtf/text -I/var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20200309-r6/work/qtwebkit-5.212.0-alpha4/Source/WTF/wtf/threads -I/var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20200309-r6/work/qtwebkit-5.212.0-alpha4/Source/WTF/wtf/unicode -I/var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20200309-r6/work/qtwebkit-5.212.0-alpha4/Source/ThirdParty -I/var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20200309-r6/work/qtwebkit-5.212.0-alpha4_build -I/var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20200309-r6/work/qtwebkit-5.212.0-alpha4_build/DerivedSources -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/glib-2.0 -isystem /usr/lib64/glib-2.0/include  -fvisibility=hidden -fvisibility-inlines-hidden -march=core2 -O2 -pipe -fno-strict-aliasing -fpermissive -fno-exceptions -fno-strict-aliasing -fno-rtti -std=c++11 -Wno-expansion-to-defined -Wall -Wextra -Wcast-align -Wformat-security -Wmissing-format-attribute -Wpointer-arith -Wundef -Wwrite-strings -fPIC  -fPIC -MD -MT Source/WTF/wtf/CMakeFiles/WTF.dir/unicode/icu/CollatorICU.cpp.o -MF Source/WTF/wtf/CMakeFiles/WTF.dir/unicode/icu/CollatorICU.cpp.o.d -o Source/WTF/wtf/CMakeFiles/WTF.dir/unicode/icu/CollatorICU.cpp.o -c /var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20200309-r6/work/qtwebkit-5.212.0-alpha4/Source/WTF/wtf/unicode/icu/CollatorICU.cpp
In file included from /usr/include/unicode/uset.h:36,
                 from /usr/include/unicode/unorm2.h:35,
                 from /usr/include/unicode/unorm.h:25,
                 from /usr/include/unicode/ucol.h:17,
                 from /var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20200309-r6/work/qtwebkit-5.212.0-alpha4/Source/WTF/wtf/unicode/icu/CollatorICU.cpp:37:
/usr/include/unicode/localpointer.h:561:26: error: parameter declared ‘auto’
  561 | template <typename Type, auto closeFunction>
      |                          ^~~~
/usr/include/unicode/localpointer.h:573:76: error: template argument 2 is invalid
  573 |     explicit LocalOpenPointer(std::unique_ptr<Type, decltype(closeFunction)> &&p)
      |                                                                            ^
/usr/include/unicode/localpointer.h:583:78: error: template argument 2 is invalid
  583 |     LocalOpenPointer &operator=(std::unique_ptr<Type, decltype(closeFunction)> &&p) {
      |                                                                              ^
/usr/include/unicode/localpointer.h:599:59: error: template argument 2 is invalid
  599 |     operator std::unique_ptr<Type, decltype(closeFunction)> () && {
      |                                                           ^
/usr/include/unicode/uset.h:358:1: note: invalid template non-type parameter
  358 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUSetPointer, USet, uset_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/unicode/unorm2.h:286:1: note: invalid template non-type parameter
  286 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUNormalizer2Pointer, UNormalizer2, unorm2_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/unicode/uenum.h:69:1: note: invalid template non-type parameter
   69 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUEnumerationPointer, UEnumeration, uenum_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/unicode/ucol.h:553:1: note: invalid template non-type parameter
  553 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUCollatorPointer, UCollator, ucol_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by stefantalpalaru** [comment]
Fixed.

**Comment by efferre79** [comment]
I have testes latest ebuild but I get another compile failure, something related to ruby:

```
FAILED: DerivedSources/JavaScriptCore/LLIntDesiredOffsets.h /var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20240528/work/qtwebkit-756e1c8f23dc2720471298281c421
c0076d02df8_build/DerivedSources/JavaScriptCore/LLIntDesiredOffsets.h
cd /var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20240528/work/qtwebkit-756e1c8f23dc2720471298281c421c0076d02df8_build/Source/JavaScriptCore && /usr/bin/ruby3
2 /var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20240528/work/qtwebkit-756e1c8f23dc2720471298281c421c0076d02df8/Source/JavaScriptCore/offlineasm/generate_offs
et_extractor.rb -I/var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20240528/work/qtwebkit-756e1c8f23dc2720471298281c421c0076d02df8_build/DerivedSources/JavaScrip
tCore/ /var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20240528/work/qtwebkit-756e1c8f23dc2720471298281c421c0076d02df8/Source/JavaScriptCore/llint/LowLevelInter
preter.asm /var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20240528/work/qtwebkit-756e1c8f23dc2720471298281c421c0076d02df8_build/DerivedSources/JavaScriptCore/L
LIntDesiredOffsets.h
/var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20240528/work/qtwebkit-756e1c8f23dc2720471298281c421c0076d02df8/Source/JavaScriptCore/offlineasm/parser.rb:587:i
n `block in parseSequence': undefined method `=~' for #<Annotation:0x00007fdb944f0610 @codeOrigin=#<CodeOrigin:0x00007fdb944f0660 @sourceFile=#<SourceFile:0
x00007fdb94368e50 @name=#<Pathname:/var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20240528/work/qtwebkit-756e1c8f23dc2720471298281c421c0076d02df8/Source/JavaSc
riptCore/llint/LowLevelInterpreter64.asm>, @fileNumber=3>, @lineNumber=511>, @type=:local, @string="Check if there are some unaligned slots we can use"> (No
MethodError)
        from /var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20240528/work/qtwebkit-756e1c8f23dc2720471298281c421c0076d02df8/Source/JavaScriptCore/offlineasm/pa
rser.rb:586:in `loop'
        from /var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20240528/work/qtwebkit-756e1c8f23dc2720471298281c421c0076d02df8/Source/JavaScriptCore/offlineasm/pa
rser.rb:586:in `parseSequence'
        from /var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20240528/work/qtwebkit-756e1c8f23dc2720471298281c421c0076d02df8/Source/JavaScriptCore/offlineasm/pa
rser.rb:654:in `block in parseSequence'
        from /var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20240528/work/qtwebkit-756e1c8f23dc2720471298281c421c0076d02df8/Source/JavaScriptCore/offlineasm/pa
rser.rb:586:in `loop'
        from /var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20240528/work/qtwebkit-756e1c8f23dc2720471298281c421c0076d02df8/Source/JavaScriptCore/offlineasm/pa
rser.rb:586:in `parseSequence'
        from /var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20240528/work/qtwebkit-756e1c8f23dc2720471298281c421c0076d02df8/Source/JavaScriptCore/offlineasm/pa
rser.rb:814:in `parseData'
        from /var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20240528/work/qtwebkit-756e1c8f23dc2720471298281c421c0076d02df8/Source/JavaScriptCore/offlineasm/parser.rb:818:in `parse'
        from /var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20240528/work/qtwebkit-756e1c8f23dc2720471298281c421c0076d02df8/Source/JavaScriptCore/offlineasm/parser.rb:780:in `block in parseSequence'
        from /var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20240528/work/qtwebkit-756e1c8f23dc2720471298281c421c0076d02df8/Source/JavaScriptCore/offlineasm/parser.rb:586:in `loop'
        from /var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20240528/work/qtwebkit-756e1c8f23dc2720471298281c421c0076d02df8/Source/JavaScriptCore/offlineasm/parser.rb:586:in `parseSequence'
        from /var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20240528/work/qtwebkit-756e1c8f23dc2720471298281c421c0076d02df8/Source/JavaScriptCore/offlineasm/parser.rb:625:in `block in parseSequence'
        from /var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20240528/work/qtwebkit-756e1c8f23dc2720471298281c421c0076d02df8/Source/JavaScriptCore/offlineasm/parser.rb:586:in `loop'
        from /var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20240528/work/qtwebkit-756e1c8f23dc2720471298281c421c0076d02df8/Source/JavaScriptCore/offlineasm/parser.rb:586:in `parseSequence'
        from /var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20240528/work/qtwebkit-756e1c8f23dc2720471298281c421c0076d02df8/Source/JavaScriptCore/offlineasm/parser.rb:814:in `parseData'
        from /var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20240528/work/qtwebkit-756e1c8f23dc2720471298281c421c0076d02df8/Source/JavaScriptCore/offlineasm/parser.rb:818:in `parse'
        from /var/tmp/portage/dev-qt/qtwebkit-5.212.0_pre20240528/work/qtwebkit-756e1c8f23dc2720471298281c421c0076d02df8/Source/JavaScriptCore/offlineasm/generate_offset_extractor.rb:68:in `<main>'

```

**Comment by stefantalpalaru** [comment]
What are your USE flags? You can see them with `emerge -pv qtwebkit`.

Also, what's your Ruby version? Visible in `eselect ruby list`.

Arch Linux uses a promising patch from Fedora, but I'm curious why I did not see this failure on my system: https://src.fedoraproject.org/rpms/qt5-qtwebkit/raw/rawhide/f/webkit-offlineasm-warnings-ruby27.patch

**Comment by efferre79** [comment]
> What are your USE flags? You can see them with `emerge -pv qtwebkit`.

```
[ebuild  NS   #] dev-qt/qtwebkit-5.212.0_pre20240528:5/5.212::stefantalpalaru [4.8.7:4::__qt4__] USE="X%* gstreamer%* hyphen%* jit nsplugin%* opengl%* printsupport%* -geolocation% -gles2-only% -multimedia% -orientation% -qml% -webp% (-aqua%) (-debug%) (-exceptions%) (-icu%*) (-pch%)" ABI_X86="(-32%*) (-64%*) (-x32%)" 0 KiB
```

> Also, what's your Ruby version? Visible in `eselect ruby list`.

```
Available Ruby profiles:
  [1]   ruby31 *
  [2]   ruby32 (with Rubygems)
```

**Comment by stefantalpalaru** [comment]
I cannot replicate your build failure, but I added that Ruby patch. Please test the new version and let me know if it works for you.

**Comment by efferre79** [comment]
I confirm that now compiles fine, thanks!
